// <auto-generated />
using System;
using FUMCFoodPantry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUMCFoodPantry.Migrations
{
    [DbContext(typeof(FUMCFoodPantryContext))]
    [Migration("20260427185622_UserDatabaseUpdate")]
    partial class UserDatabaseUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Served")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UserApplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Family1Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family1Ethnicity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family1Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Family1Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family1Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Family2Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family2Ethnicity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family2Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Family2Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family2Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Family3Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family3Ethnicity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family3Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Family3Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family3Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family3Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Family4Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family4Ethnicity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family4Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Family4Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family4Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family4Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Family5Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family5Ethnicity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family5Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Family5Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family5Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family5Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixedAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HosuingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Household")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Military")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vetran")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
